from turtle import *

goto(-240, 240)
#def trojkat(d):

def z(w):
    for i in range(0,20):
        kolor = 'green'
        fillcolor(kolor)
        begin_fill()
        forward(w)
        right(90)
        forward(w)
        right(90)
        forward(w)
        right(90)
        forward(w)
        right(90)
        forward(w)
        end_fill()
def x(w):
    for i in range(0,18):
        kolor = 'orange'
        fillcolor(kolor)
        begin_fill()
        forward(w)
        right(90)
        forward(w)
        right(90)
        forward(w)
        right(90)
        forward(w)
        right(90)
        forward(w)
        end_fill()
def trujkat(w):
    print(krutki(w))
    print(dlugi(w))
    forward(w)
    left(90)
    print(krutki(w))
    print(dlugi(w))
    forward(w)
    left(90)
    print(krutki(w))
    print(dlugi(w))
    forward(w)
    left(90)
    print(krutki(w))
    print(dlugi(w))


def dlugi(w):
    for i in range(0,7):
        kolor = 'green'
        fillcolor(kolor)
        begin_fill()
        forward(2*w)
        left(135)
        forward(33.94)
        left(90)
        forward(33.94)
        left(135)
        forward(2 * w)
        end_fill()

def krutki(w):
    kolor = 'green'
    fillcolor(kolor)
    begin_fill()
    forward(w)
    left(135)
    forward(33.94)
    left(135)
    forward(w)
    left(90)
    forward(w)
    end_fill()

def duzykwadrat(w):
    for i in range(0,3):
        print(orange(w))
        right(180)
        forward(w)
        right(90)

    print(green(w))
    right(180)
    forward(w)
    right(90)

    for i in range(0, 3):
        print(orange(w))
        right(180)
        forward(w)
        right(90)

    right(90)
    forward(3*w)
    right(90)
    print(orange(w))
    left(90)
    forward(w)
    print(orange(w))
    left(90)
    forward(w)
    print(orange(w))
    right(90)
    forward(3 * w)
    right(90)
    print(orange(w))
    right(180)
    forward(w)
    right(90)
    print(orange(w))
    right(180)
    forward(w)
    right(90)
    print(orange(w))
    print(czerwony(w))
    right(90)
    forward(w)
    print(czerwony(w))
    right(90)
    forward(w)
    right(90)
    forward(w)
    print(czerwony(w))
    forward(w)
    right(90)
    forward(w)
    left(180)
    print(czerwony(w))
    right(90)
    forward(w)
    print(czerwony(w))
    right(90)
    forward(w)
    right(90)
    forward(w)
    print(czerwony(w))
    forward(w)
    right(90)
    forward(w)
    left(180)
    print(czerwony(w))
    right(90)
    forward(w)
    print(czerwony(w))
    right(90)
    forward(w)
    right(90)
    forward(w)
    print(czerwony(w))
    forward(w)
    right(90)
    forward(w)
    left(180)
    print(czerwony(w))
    right(90)
    forward(w)
    print(czerwony(w))
    right(90)
    forward(w)
    right(90)
    forward(w)
    print(czerwony(w))

def orange(w):
    kolor = 'orange'
    fillcolor(kolor)
    begin_fill()
    forward(w)
    left(90)
    forward(w)
    left(90)
    forward(w)
    left(90)
    forward(w)
    end_fill()

def green(w):
    kolor = 'green'
    fillcolor(kolor)
    begin_fill()
    forward(w)
    left(90)
    forward(w)
    left(90)
    forward(w)
    left(90)
    forward(w)
    end_fill()

def czerwony(w):
    kolor = 'red'
    fillcolor(kolor)
    begin_fill()
    forward(w)
    right(90)
    forward(w)
    right(90)
    forward(w)
    right(90)
    forward(w)
    end_fill()

def dywan(w):
    for i in range(0,4):
        print(z(w))
        right(90)
    forward(w)
    right(90)
    forward(w)
    left(90)
    for i in range(0,4):
        print(x(w))
        right(90)
    forward(w)
    right(90)
    forward(w)
    print(trujkat(w))
    left(45)
    print(duzykwadrat(33.94))
    forward(11*33.94)
    left(90)
    forward(33.94)
    right(90)
    forward(33.94)
    left(90)
    print(duzykwadrat(33.94))
    forward(4*33.94)
    right(90)
    forward(6 * 33.94)
    left(90)
    print(duzykwadrat(33.94))
    forward(10 * 33.94)
    left(90)
    forward(33.94)
    right(90)
    forward(2*33.94)
    left(90)
    print(duzykwadrat(33.94))

    forward(33.94)
    right(90)
    forward(2 * 33.94)
    left(90)

    for i in range(0, 7):
        kolor = 'green'
        fillcolor(kolor)
        begin_fill()
        forward(33.94)
        left(90)
        forward(33.94)
        left(90)
        forward(33.94)
        left(90)
        forward(33.94)
        end_fill()
        left(90)
        forward(33.94)
        forward(33.94)
        left(90)
        forward(33.94)
        left(90)
        forward(33.94)
        left(180)

    left(180)
    forward(7 * 33.94)
    left(90)

    for i in range(0, 7):
        kolor = 'green'
        fillcolor(kolor)
        begin_fill()
        forward(33.94)
        left(90)
        forward(33.94)
        left(90)
        forward(33.94)
        left(90)
        forward(33.94)
        end_fill()
        left(90)
        forward(33.94)
        forward(33.94)
        left(90)
        forward(33.94)
        left(90)
        forward(33.94)
        left(180)

speed(0)
print(dywan(24))
exitonclick()