# https://logia.oeiizk.waw.pl/strony/archiwalne/L22_zadania_e1.pdf
from turtle import *
def zielony(bok,kolor):
    zero = pos()
    pd()
    fillcolor(kolor)
    begin_fill()
    goto(zero[0]+bok*2,zero[1])
    goto(zero[0]+bok*2, zero[1]+bok*2)
    goto(zero[0], zero[1]+bok*2)
    goto(zero[0], zero[1])
    end_fill()
    pu()

def strzalkaPG(bok,kolor):
    pd()
    forward(bok*2)
    zero = pos()
    fillcolor(kolor)
    begin_fill()
    goto(zero[0] - (bok / 2), zero[1] + (bok / 2))
    goto(zero[0] - (bok), zero[1])
    goto(zero[0] - (bok * 2), zero[1]+bok)
    goto(zero[0] - (bok + (bok/2)), zero[1] + (bok + (bok/2)))
    goto(zero[0] - (bok * 2), zero[1] + (bok * 2))
    goto(zero[0] - (bok*2), zero[1])
    end_fill()
    pu()


def strzalkaPD(bok, kolor):
    pd()
    zero = pos()
    fillcolor(kolor)
    begin_fill()
    goto(zero[0] +(bok/2), zero[1]+(bok/2))
    goto(zero[0] , zero[1]+bok)
    goto(zero[0]+bok , zero[1]+bok*2)
    goto(zero[0] + (bok + (bok/2)),zero[1]+ (bok + (bok/2)))
    goto(zero[0]+bok*2 , zero[1]+bok*2)
    goto(zero[0] , zero[1]+bok*2)
    goto(zero[0], zero[1])
    end_fill()
    pu()


def strzalkaLG(bok,kolor):
    pd()
    zero = pos()
    fillcolor(kolor)
    begin_fill()
    goto(zero[0]+bok/2, zero[1]+bok/2)
    goto(zero[0]+bok, zero[1])
    goto(zero[0]+bok*2, zero[1]+bok)
    goto(zero[0]+ (bok + (bok/2)), zero[1]+ (bok + (bok/2)))
    goto(zero[0]+bok*2, zero[1]+bok*2)
    goto(zero[0]+bok*2, zero[1])
    goto(zero[0], zero[1])
    end_fill()
    pu()


def strzalkaLD(bok,kolor):
    pd()
    zero = pos()
    fillcolor(kolor)
    begin_fill()
    goto(zero[0]+bok*2, zero[1])
    goto(zero[0]+(bok+(bok/2)), zero[1]+bok/2)
    goto(zero[0]+bok*2, zero[1]+bok)
    goto(zero[0]+bok, zero[1]+bok*2)
    goto(zero[0]+bok/2, zero[1]+(bok + (bok/2)))
    goto(zero[0], zero[1]+bok*2)
    goto(zero[0]+bok*2, zero[1]+bok*2)
    goto(zero[0]+bok*2, zero[1])
    end_fill()
    pu()

def jeden(bok, kolor):
    zero = pos()
    goto(zero[0], zero[1] - (bok * 5))
    forward(bok)
    zielony(bok,kolor)
    strzalkaLG(bok, 'white')
    left(90)
    forward(bok*2)
    left(90)
    forward(bok)
    left(180)
    zielony(bok, kolor)
    strzalkaPG(bok, 'white')
    forward(bok*2)
    left(90)
    forward(bok)
    zielony(bok, kolor)
    strzalkaPD(bok, 'white')
    right(90)
    forward(bok)
    right(90)
    forward(bok*2)
    left(90)
    zielony(bok, kolor)
    strzalkaLD(bok, 'white')


def dywan():
    pu()
    goto(-200, 200)
    pd()
    kolor = 'tomato'
    fillcolor(kolor)
    begin_fill()
    goto(200, 200)
    goto(200, -200)
    goto(-200, -200)
    goto(-200, 200)
    end_fill()
    bok = 400 / 10
    pu()
    jeden(bok, "green")
    goto(0,0)
    jeden(bok, "green")
    goto(0,bok*5)
    jeden(bok, "green")
    goto(-(bok * 5), 0)
    jeden(bok, "green")
    goto(0,0)
    pd()
    goto(-(bok * 5), 0)
    goto((bok * 5), 0)
    goto(0,0)
    goto(0, -(bok * 5))
    goto(0, (bok * 5))
    pu()

speed(0)
dywan()

exitonclick()